site_name: Black MIDI Guides
site_description: Guides for a bunch of things people often ask for help with in Black MIDI Communities
site_author: 6gh
site_url: https://guides.blackmidi.wiki/

repo_url: https://github.com/OvertureMIDI/Guides
repo_name: Black-MIDI-Guides
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 6gh

theme:
    name: material
    logo: assets/logo.svg
    favicon: assets/logo.svg
    icon:
        annotation: material/arrow-right-circle
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tabs
        - search.highlight
        - content.action.view
        - content.action.edit
        - content.tabs.link
        - content.code.copy
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

plugins:
    - privacy
    - awesome-pages
    - git-authors:
          show_email_address: false
          sort_authors_by: name
          show_contribution: false
          exclude:
              - index.md
    - git-revision-date-localized:
          fallback_to_build_date: true
          type: date
          exclude:
              - index.md

markdown_extensions:
    - admonition
    - pymdownx.details
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          anchor_linenums: true
          use_pygments: true
    - pymdownx.tabbed:
          alternate_style: true
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - toc:
          permalink: true

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/OvertureMIDI/Guides
          name: GitHub Repository
        - icon: material/email-edit
          link: mailto:contact@blackmidi.wiki
          name: Contact Email
