site_name: Black MIDI Guides
site_description: Guides for a bunch of things people often ask for help with in Black MIDI Communities
site_author: 6gh
site_url: https://guides.blackmidi.wiki/

repo_url: https://github.com/6gh/Black-MIDI-Guides
repo_name: Black-MIDI-Guides

copyright: Copyright &copy; 2024 6gh

theme:
    name: material
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tabs
        - search.highlight
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
plugins:
    - privacy
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
